export default {
  'daily': 1,
  'tabloid': -3,
  'liberal': -3,
  'centre-right': -1,
  'compact': 0,
  'labour': -3,
  'red': -5,
  'conservative': -3,
  'broadsheet': 2,
  'freesheet': -4,
  'pro-europeanism': -2,
  'weekly newspaper': -1,
  'conservatism': -3,
  'centre': 3,
  'online': -1,
  'website': -1,
  'sunday': 0,
  'snp': -3,
  'fine gael': -3,
  'labour party': -3,
  'unionist': -3,
  'centre-left': -1,
  'berliner': 1,
  'regional': -1,
  'free': -4,
  'euroscepticism': -5,
  'right-wing': -7,
  'left-wing': -7,
  'right': -3,
  'left': -3,
  'populism': -7,
  'centrist': 3,
  'populist': -7
}
